### ISSUE TITLE
missed imports

### ISSUE THREAD

**Issue by philippemerle** [xlab-si/xopera-examples#28]
We should assume that a TOSCA type used in a service template file shall be 1) defined in this file, or 2) defined in one of imported files, or 3) a TOSCA normative type. Several xOpera examples files use types undefined, i.e., import definitions are missed.

For instance, [cloud/aws/thumbnail-generator-with-api-gateway/modules/lambda/lambda.yaml](https://github.com/xlab-si/xopera-examples/blob/master/cloud/aws/thumbnail-generator-with-api-gateway/modules/lambda/lambda.yaml) uses the type `radon.nodes.aws.api_gateway` but this type is not defined locally and there is no import definition. Adding an import definition to [lambda.yaml](https://github.com/xlab-si/xopera-examples/blob/master/cloud/aws/thumbnail-generator-with-api-gateway/modules/lambda/lambda.yaml), i.e.
```
imports:
  - ../bucket_notification/bucket_notification.yaml
```
resolves this issue.

**Comment by philippemerle** [comment]
Files where an undefined type is used, i.e. an import definition is missed, are:
* cloud/aws/thumbnail-generator-with-api-gateway/modules/lambda/lambda.yaml
* cloud/aws/thumbnail-generator-with-api-gateway/modules/lambda_role/lambda_role.yaml
* cloud/aws/thumbnail-generator-with-vm/modules/ec2_keypair/ec2_keypair.yaml
* cloud/aws/thumbnail-generator-with-vm/modules/ec2_role/ec2_role.yaml
* cloud/aws/thumbnail-generator-with-vm/modules/lambda/lambda.yaml
* cloud/aws/thumbnail-generator-with-vm/modules/lambda_role/lambda_role.yaml
* cloud/aws/thumbnail-generator-with-vm/modules/vpc_subnet/vpc_subnet.yaml
* cloud/aws/thumbnail-generator/modules/lambda/lambda.yaml
* cloud/aws/thumbnail-generator/modules/lambda_role/lambda_role.yaml
* cloud/platform-connection/aws-azure-connection/aws-azure/modules/aws/aws_role/aws_role.yaml
* cloud/platform-connection/aws-azure-connection/aws-azure/modules/aws/lambda/aws_lambda.yaml
* cloud/platform-connection/aws-azure-connection/aws-azure/modules/azure/function-deploy/azure_function.yaml
* cloud/platform-connection/aws-azure-connection/aws-azure/modules/transfer/lambda/transfer_lambda.yaml
* cloud/platform-connection/aws-azure-connection/azure-aws/modules/aws/aws_role/aws_role.yaml
* cloud/platform-connection/aws-azure-connection/azure-aws/modules/aws/lambda/aws_lambda.yaml
* misc/nginx-openstack/library/nginx/server/types.yaml
* misc/nginx-openstack/library/nginx/site/types.yaml

**Comment by philippemerle** [comment]
See PR https://github.com/xlab-si/xopera-examples/pull/29

**Comment by anzoman** [comment]
@philippemerle thanks a lot for spotting and correctinge these issues!
