### ISSUE TITLE
tosca.capabilities.Compute is incompatible with tosca.relationships.DependsOn

### ISSUE THREAD

**Issue by philippemerle** [xlab-si/xopera-examples#30]
Several xOpera examples define requirements like:
```
  requirements:
    - <requirement_name>:
         capability: tosca.capabilities.Compute
         relationship: tosca.relationships.DependsOn
```
But `tosca.capabilities.Compute` is incompatible with valid target types of `tosca.relationships.DependsOn`, aka `[ tosca.capabilities.Node ]`.

Line `capability: tosca.capabilities.Compute` should be replaced by `capability: tosca.capabilities.Node` in following files:
* cloud/aws/thumbnail-generator-with-api-gateway/modules/api_gateway/api_gateway.yaml
* cloud/aws/thumbnail-generator-with-vm/modules/bucket_notification/bucket_notification.yaml
* cloud/aws/thumbnail-generator/modules/bucket_notification/bucket_notification.yaml
* cloud/platform-connection/aws-azure-connection/aws-azure/modules/aws/bucket_notification/aws_bucket_notification.yaml
* cloud/platform-connection/aws-azure-connection/aws-azure/modules/transfer/bucket_notification/transfer_bucket_notification.yaml
* cloud/platform-connection/aws-azure-connection/aws-azure/modules/transfer/lambda/transfer_lambda.yaml
* cloud/platform-connection/aws-azure-connection/azure-aws/modules/aws/bucket_notification/aws_bucket_notification.yaml
* kubernetes/rancher/lib/prometheus-helm-chart/prometheus-helm-chart.yaml
* csars/misc-tosca-types/modules/node_types/setter/setter.yaml

**Comment by philippemerle** [comment]
Line `capability: tosca.capabilities.Root` should be replaced by `capability: tosca.capabilities.Node` in following files:
* tosca/attribute-mapping/service.yaml
* tosca/capability-attributes-properties/service.yaml

**Comment by anzoman** [comment]
@philippemerle many thanks for finding and fixing these TOSCA inconsistincies!
