### ISSUE TITLE
unfulfilled mandatory requirements

### ISSUE THREAD

**Issue by philippemerle** [xlab-si/xopera-examples#31]
Some mandatory requirements are not fulfilled:
* xopera-examples/cloud/platform-connection/aws-azure-connection/aws-azure/service.yaml:topology_template:node_templates:aws_lambda:requirements:bucket
* xopera-examples/cloud/platform-connection/aws-azure-connection/azure-aws/service.yaml:topology_template:node_templates:aws_lambda:requirements:bucket
* xopera-examples/cloud/aws/thumbnail-generator-with-api-gateway/service.yaml:topology_template:node_templates:lambda:requirements:bucket
* xopera-examples/cloud/aws/thumbnail-generator-with-vm/service.yaml:topology_template:node_templates:lambda:requirements:bucket
* xopera-examples/cloud/aws/thumbnail-generator/service.yaml:topology_template:node_templates:lambda:requirements:bucket
* xopera-examples/misc/scaling/service.yaml:topology_template:node_templates:aws_lambda:requirements:host
* xopera-examples/tosca/artifacts/service.yaml:topology_template:node_templates:artifacts_file:requirements:host

**Comment by philippemerle** [comment]
See PR https://github.com/xlab-si/xopera-examples/pull/32

**Comment by anzoman** [comment]
@philippemerle thanks for spotting this one too!
